version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_ID}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

  api-server:
    image: node:14
    container_name: api-server
    working_dir: /app/api-server
    volumes:
      - ./:/app
      - /app/api-server/node_modules
      - /app/shared/node_modules
    env_file:
      - .env
    command: sh -c "cd /app && npm install && cd /app/api-server && npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb

  mqtt-server:
    image: node:14
    container_name: mqtt-server
    working_dir: /app/mqtt-server
    volumes:
      - ./:/app
      - /app/mqtt-server/node_modules
      - /app/shared/node_modules
    env_file:
      - .env
    command: sh -c "cd /app && npm install && cd /app/mqtt-server && npm install && npm start"
    ports:
      - "1883:1883"
    depends_on:
      - timescaledb

volumes:
  timescale-data: