version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_ID}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

  api-server:
    image: copeve1015/api-server:latest
    container_name: api-server
    working_dir: /app/api-server
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb

  mqtt-ws-server:
    image: copeve1015/mqtt-ws-server:latest
    secrets:
      - aws_iot_private_key
      - aws_iot_certificate
      - aws_iot_root_ca
    container_name: mqtt-ws-server
    working_dir: /app/mqtt-ws-server
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - timescaledb

  ai-server:
    image: copeve1015/ai-server:latest
    container_name: ai-server
    working_dir: /app/ai-server
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb

secrets:
  aws_iot_private_key:
    file: ./secrets/private.pem.key
  aws_iot_certificate:
    file: ./secrets/certificate.pem.crt
  aws_iot_root_ca:
    file: ./secrets/root-ca.pem

volumes:
  timescale-data: