version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_ID}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

  api-server:
    build:
      context: .
      dockerfile: api-server/Dockerfile
    container_name: api-server
    working_dir: /app/api-server
    volumes:
      - ./api-server:/app/api-server
      - ./shared:/app/shared
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb

  mqtt-ws-server:
    build:
      context: .
      dockerfile: mqtt-ws-server/Dockerfile
    container_name: mqtt-ws-server
    working_dir: /app/mqtt-ws-server
    volumes:
      - ./mqtt-ws-server:/app/mqtt-ws-server
      - ./shared:/app/shared
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - timescaledb

volumes:
  timescale-data:
