version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_ID}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

  express:
    image: node:14
    container_name: express
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb

volumes:
  timescale-data:
